### ISSUE TITLE
config should not force building layout

### ISSUE THREAD

**Issue by ede1998** [ede1998/smartknx#1]
The config files should be more generic.

Suggestion
- one container type for pages
- one box for subsections of 
- those can be nested infinitely

```yaml
project: the project name
pages:
  - name: page title
  - url: url_for_page
  - pages: # optional, can be nested
    - name: subpage
    - url: sp
    - boxes:
      - Light:
          read: 1/2/3 # knx group address for reads
          write: 4/5/6 # knx group address for writes
          name: display name
```
